openapi: 3.0.0
info:
  title: Legislation Extraction API
  version: "1.0"
paths:
  /extract-data:
    post:
      summary: Estrae dati legislativi.
      operationId: normapi.norma_scraper
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                 act_type:
                  type: string
                  example: legge
                 date:
                   type: string
                   example: 7 agosto 1990
                 act_number:
                   type: string
                   example: "241"
                 article:
                   type: string
                   example: "1"
                   default: ""
                   nullable: false
                 extension:
                   type: string
                   default: ""
                   nullable: false
                 comma:
                   type: string
                   default: ""
                   nullable: false
                 version:
                   type: string
                   default: vigente
                   nullable: false
                 version_date:
                   type: string
                   format: date
                   default: ""
                   nullable: false
                 timeout:
                   type: integer
                   default: 10
      responses:
        '200':
          description: Dati estratti con successo.
          content:
            application/xml:
              schema:
                type: string
            text/html:
              schema:
                type: string
        '400':
          description: Richiesta non valida.
        '500':
          description: Errore server.
